pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - status-success=CI
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
