on:
  push

name: CI
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build container
      uses: ./.github/make/
      with:
        args: build
